services:
  - type: web
    name: idea-hub
    env: node
    buildCommand: npm run build
    startCommand: node dist/server/index.js
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
